name: shows_vault
description: "Discover your favorite movies and TV shows"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  husky: ^0.1.7
  commitlint_cli: ^0.7.2

flutter:
  uses-material-design: true
